# Generated by Django 5.2 on 2025-05-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("experiencia", models.IntegerField()),
                ("asignaturas", models.CharField(max_length=255)),
                ("fp", models.CharField(max_length=100)),
                ("imagen", models.ImageField(upload_to="profesores/")),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
    ]
