# Generated by Django 5.2 on 2025-05-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inicio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profesor",
            name="apellido",
            field=models.CharField(default="Sin apellido", max_length=100),
        ),
        migrations.AddField(
            model_name="profesor",
            name="centros_trabajo",
            field=models.TextField(default="Sin apellido"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profesor",
            name="formacion",
            field=models.TextField(default="Sin apellido"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profesor",
            name="imagen",
            field=models.ImageField(upload_to="imagenes_profesores/"),
        ),
    ]
